### ISSUE TITLE
Support Gromacs 2021

### ISSUE THREAD

**Issue by scal444** [scal444/gromax#28]

**Comment by kexul** [comment]
Hopefully gromacs 2021 will be supported soon!

**Comment by scal444** [comment]
> Hopefully gromacs 2021 will be supported soon!

I'll try to get it out this weekend! I don't actually think there's much at all to change between 2020 and 2021, but I'll run some tests on my desktop.

Please let me know if there's any other features you'd like to see. My main priority is issue #26 since I think the biggest problem with Gromax right now is it generates a lot of possibilities that are reaaaaallly unlikely to be the most performant.

**Comment by scal444** [comment]
This is now merged in master, so feel free to try it out! Also, any script built for gmx 2020 should work as well - from my testing, they're compatible with the options gromax explores. It'll also be in v1.1, but I have a few features more for that.

**Comment by scal444** [comment]
Now in v0.2.0
